//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Użytkownicy
    {
        public Użytkownicy()
        {
            this.AspNetUserLogins = new HashSet<AspNetUserLogins>();
            this.Zlecenie = new HashSet<Zlecenie>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaims>();
            this.AspNetRoles = new HashSet<Role_Użytkowników>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual ICollection<Zlecenie> Zlecenie { get; set; }
        public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual ICollection<Role_Użytkowników> AspNetRoles { get; set; }
    }
}
