//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zlecenie
    {
        public int ZlecenieID { get; set; }
        public string Miejsce_nadania { get; set; }
        public string Miejsce_dostawy { get; set; }
        public string Odbiorca { get; set; }
        public string Zleceniodawca { get; set; }
        public string Zawartosc { get; set; }
        public Nullable<int> Ilosc_opakowan { get; set; }
        public string Rodzaj_opakowan { get; set; }
        public bool Materialy_niebezpieczne { get; set; }
        public bool Pobranie_za_przesylke { get; set; }
        public bool Priorytet { get; set; }
        public string Kategoria_zlecenia { get; set; }
        public string Kurier { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
