SET IDENTITY_INSERT [dbo].[Zlecenie] ON
INSERT INTO [dbo].[Zlecenie] ([ZlecenieID], [Miejsce_nadania], [Miejsce_dostawy], [Odbiorca], [Zleceniodawca], [Ilosc_opakowan], [Materialy_niebezpieczne], [Pobranie_za_przesylke], [Priorytet], [Kurier], [Status], [Komentarz_kuriera], [Komentarz_nadawcy], [RodzajOpakowaniaId], [ZawartoscId], [PowodOdrzuceniaId], [PowodPrzelozeniaId], [RodzajZleceniaId]) VALUES (2, N'Międzynarodowa 15, 02-212 Warszawa', N'Dzielna 6, 00-123 Warszawa', N'Marta Karcz', N'Marek Białas', 1, 0, 1, 1, N'6206b761-b094-4513-a632-531d4c38c98d', 5, NULL, NULL, 1, 1, 4, NULL, 1)
INSERT INTO [dbo].[Zlecenie] ([ZlecenieID], [Miejsce_nadania], [Miejsce_dostawy], [Odbiorca], [Zleceniodawca], [Ilosc_opakowan], [Materialy_niebezpieczne], [Pobranie_za_przesylke], [Priorytet], [Kurier], [Status], [Komentarz_kuriera], [Komentarz_nadawcy], [RodzajOpakowaniaId], [ZawartoscId], [PowodOdrzuceniaId], [PowodPrzelozeniaId], [RodzajZleceniaId]) VALUES (3, N'Trakt Królewski 197, 05-083 Borzęcin Duzy', N'Odkryta 11c, 02-121 Warszawa', N'Marcin Szczur', N'Tomasz Bodo', 1, 0, 0, 0, N'6206b761-b094-4513-a632-531d4c38c98d', 5, NULL, NULL, 1, 1, NULL, NULL, 1)
INSERT INTO [dbo].[Zlecenie] ([ZlecenieID], [Miejsce_nadania], [Miejsce_dostawy], [Odbiorca], [Zleceniodawca], [Ilosc_opakowan], [Materialy_niebezpieczne], [Pobranie_za_przesylke], [Priorytet], [Kurier], [Status], [Komentarz_kuriera], [Komentarz_nadawcy], [RodzajOpakowaniaId], [ZawartoscId], [PowodOdrzuceniaId], [PowodPrzelozeniaId], [RodzajZleceniaId]) VALUES (4, N'Międzynarodowa 15, 02-212 Warszawa', N'Odkryta 11c, 02-121 Warszawa', N'Tomasz Izdebski', N'Karol MIły', 1, 0, 1, 0, N'ba0cb2d1-cbd9-489d-9e6c-c720863af907', 2, NULL, NULL, 1, 1, NULL, NULL, 1)
INSERT INTO [dbo].[Zlecenie] ([ZlecenieID], [Miejsce_nadania], [Miejsce_dostawy], [Odbiorca], [Zleceniodawca], [Ilosc_opakowan], [Materialy_niebezpieczne], [Pobranie_za_przesylke], [Priorytet], [Kurier], [Status], [Komentarz_kuriera], [Komentarz_nadawcy], [RodzajOpakowaniaId], [ZawartoscId], [PowodOdrzuceniaId], [PowodPrzelozeniaId], [RodzajZleceniaId]) VALUES (5, N'Trakt Królewski 197, 05-083 Borzęcin Duzy', N'Dzielna 6, 00-123 Warszawa', N'Marta Karcz', N'Jan Dołęga', 1, 1, 1, 0, N'ba0cb2d1-cbd9-489d-9e6c-c720863af907', 2, NULL, NULL, 2, 1, NULL, NULL, 1)
INSERT INTO [dbo].[Zlecenie] ([ZlecenieID], [Miejsce_nadania], [Miejsce_dostawy], [Odbiorca], [Zleceniodawca], [Ilosc_opakowan], [Materialy_niebezpieczne], [Pobranie_za_przesylke], [Priorytet], [Kurier], [Status], [Komentarz_kuriera], [Komentarz_nadawcy], [RodzajOpakowaniaId], [ZawartoscId], [PowodOdrzuceniaId], [PowodPrzelozeniaId], [RodzajZleceniaId]) VALUES (6, N'Krucza 6, 02-111 Warszawa', N'Królewska 16, 00-103 Warszawa', N'Marcin Szczur', N'Tomasz Bodo', 1, 0, 1, 1, N'ba0cb2d1-cbd9-489d-9e6c-c720863af907', 2, NULL, NULL, 1, 1, NULL, NULL, 1)
INSERT INTO [dbo].[Zlecenie] ([ZlecenieID], [Miejsce_nadania], [Miejsce_dostawy], [Odbiorca], [Zleceniodawca], [Ilosc_opakowan], [Materialy_niebezpieczne], [Pobranie_za_przesylke], [Priorytet], [Kurier], [Status], [Komentarz_kuriera], [Komentarz_nadawcy], [RodzajOpakowaniaId], [ZawartoscId], [PowodOdrzuceniaId], [PowodPrzelozeniaId], [RodzajZleceniaId]) VALUES (7, N'Krucza 6, 02-111 Warszawa', N'Złota 12, 00-104 Warszawa', N'Mariusz Ziom', N'Marek Białas', 2, 0, 1, 0, N'ba0cb2d1-cbd9-489d-9e6c-c720863af907', 2, NULL, NULL, 1, 1, NULL, NULL, 1)
INSERT INTO [dbo].[Zlecenie] ([ZlecenieID], [Miejsce_nadania], [Miejsce_dostawy], [Odbiorca], [Zleceniodawca], [Ilosc_opakowan], [Materialy_niebezpieczne], [Pobranie_za_przesylke], [Priorytet], [Kurier], [Status], [Komentarz_kuriera], [Komentarz_nadawcy], [RodzajOpakowaniaId], [ZawartoscId], [PowodOdrzuceniaId], [PowodPrzelozeniaId], [RodzajZleceniaId]) VALUES (8, N'Czerniakowska 12, 01-111 Warszawa', N'Leszno 16, 02-122 Warszawa', N'Marta Stakt', N'Miron Waśnik', 1, 0, 1, 1, N'ba0cb2d1-cbd9-489d-9e6c-c720863af907', 2, NULL, NULL, 2, 1, NULL, NULL, 1)
SET IDENTITY_INSERT [dbo].[Zlecenie] OFF
